version: '3.1'

services:

  # DATABASE MONGODB
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    command: "--auth"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    volumes:
      - crowdfunding-db:/data/db
    networks:
      - crowdfunding-backend-network

#  # DATABASE MONGODB UI
#  mongodb-express:
#    image: mongo-express
#    container_name: mongodb-express
#    restart: always
#    ports:
#      - 8088:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
#      ME_CONFIG_MONGODB_SERVER: mongodb
#    networks:
#      - crowdfunding-backend-network


  # FRONT-END
  crowdfunding-ui:
    image: crowdfundingapp-development:v1.1
    container_name: crowdfunding-ui
    ports:
      - 4200:80
    networks:
      - crowdfunding-frontend-network
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf


  # BACK-END
  registry-service:
    image: registry-service-development:v1.0
    container_name: registry-service
    ports:
      - 8761:8761
    networks:
      - crowdfunding-backend-network
    environment:
      - JWTKEY=${JWTKEY}
      - JWTISSUER=${JWTISSUER}


  users-service:
    image: users-development:v1.0
    container_name: users-service
    ports:
      - 8082:8082
    networks:
      - crowdfunding-backend-network
    environment:
      - JWTKEY=${JWTKEY}
      - JWTISSUER=${JWTISSUER}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - eureka.client.serviceUrl.defaultZone=http://registry-service:8761/eureka/
      - eureka.instance.preferIpAddress=true


  projects-service:
    image: projects-development:v1.0
    container_name: projects-service
    ports:
      - 8083:8083
    networks:
      - crowdfunding-backend-network
    environment:
      - JWTKEY=${JWTKEY}
      - JWTISSUER=${JWTISSUER}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - eureka.client.serviceUrl.defaultZone=http://registry-service:8761/eureka/
      - eureka.instance.preferIpAddress=true


  investments-service:
    image: investments-development:v1.0
    container_name: investments-service
    ports:
      - 8084:8084
    networks:
      - crowdfunding-backend-network
    environment:
      - JWTKEY=${JWTKEY}
      - JWTISSUER=${JWTISSUER}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - eureka.client.serviceUrl.defaultZone=http://registry-service:8761/eureka/
      - eureka.instance.preferIpAddress=true


  api-gateway-service:
    image: api-gateway-development:v1.0
    container_name: api-gateway-service
    ports:
      - 8081:8081
    networks:
      - crowdfunding-backend-network
      - crowdfunding-frontend-network
    environment:
      - JWTKEY=${JWTKEY}
      - JWTISSUER=${JWTISSUER}
      - eureka.client.serviceUrl.defaultZone=http://registry-service:8761/eureka/
      - eureka.instance.preferIpAddress=true

networks:
  crowdfunding-backend-network:
    driver: bridge
  crowdfunding-frontend-network:
    driver: bridge

volumes:
  crowdfunding-db:



