spring:
  application:
    name: INVESTMENTS-SERVICE
server:
  port: 8084
  include-message: always

logging:
  level:
    org:
      springframework:
        web: DEBUG


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

